### ISSUE TITLE
Account bloccati

### ISSUE THREAD

**Issue by nickjack0310** [Aniell4/DiscordHTTPGen#1]
Ciao, 
volevo solo dirti che il generatore a quanto pare fa lockare i token col numero di telefono subito dopo che vengono registrati,
cioò non sarebbe un problema se, una volta inserito il numero di telefono non venissero lockati definitivamente.
Ho provato molte volte a fare un generatore ma a quanto pare succede lo stesso anche a me, anche calcolando tutti gli headers necessari, ottenendo la fingerprint e il resto. Ho pure automatizzato il processo di verifica del telefono, ma niente vengono bloccati lo stesso.

In caso ti andasse di discuterne e collabolare mandami la richiesta su discord Bellissimo#4978

**Comment by Aniell4** [comment]
Questo generatore lo ho reso publico proprio per farlo patchare da discord, essendo una vecchia versione che ormai non usiamo.
La nuova versione, ovviamente privata, funziona perfettamente (aka crea account non lockati anche se non verifichi l'email).
Se vuoi fare funzionare un generatore ti consiglio di usare come base questo qua dato che è uno dei migliori che puoi trovare su github imo.

**Comment by nickjack0310** [comment]
Ho provato di tutto: stiamo facendo un progetto abbastanza interessante e questo generatore sarebbe un pezzo di esso, ho provato a copiare richiesta per richiesta, header e payload quelle che fa discord ma niente, continua a bloccarmeli e non capisco il perchè. Ti posso chiedere una mano solo per questo piccolo passaggio?

**Comment by Aniell4** [comment]
No mi dispiace ma non posso dare più consigli di quelli che ho dato postando questo generatore, dato che più persone hanno un generatore funzionante, peggio è per me e il mio team.
